---
title: 'Random effects Demo code'
author: 'Ben Whalley'
date: "Feb 2021"
bibliography: [references.bib]
biblio-style: apa6
link-citations: yes
output:
  webex::html_clean
---



```{r, include=F, message=F, warning=F}
library(tidyverse)
library(lmerTest)
library(pander)
```



```{r}
pigs <- read_csv('http://bit.ly/psystats-pigs')

```


```{r}
pigs %>%
  ggplot(aes(week, weight)) +
  geom_point(alpha=.2) +
  geom_smooth(se=F) +
  scale_x_continuous(breaks=1:10)

```




```{r}
pigs %>%
  ggplot(aes(week, weight,  group=id)) +
  geom_point(alpha=.2) +
  geom_smooth(se=F, size=.2, color="black") +
  scale_x_continuous(breaks=1:10)

```






```{r}
pigs.ri <- lmer(weight ~ 1 + week + (1|id), data=pigs)
summary(pigs.ri)
```



```{r}
pigs.ri %>% fixef()
m1.varcor <- pigs.ri %>% VarCorr() %>% as_tibble()
```




```{r}
pigs.rs <- lmer(weight ~ week + (1 + week|id), data=pigs)
m2.varcor <- pigs.ri %>% VarCorr() %>% as_tibble()

bind_rows(m1.varcor, m2.varcor)
```













Correlation of random effects

```{r}
summary(pigs.rs)

pigs.ri.nocor <- lmer(weight ~ 1 + week + (1|id) + (0 + week | id), data=pigs)

# it makes model worse
anova(pigs.ri, pigs.ri.nocor)

```


R squared


```{r}
library(MuMIn)
pigs.ri <- lmer(weight ~ week + (1|id), data=pigs)
r.squaredGLMM(pigs.ri) %>% as_tibble() %>% mutate_all(round, digits=2) %>%  pander()
```




